development:
  adapter: postgresql
  encoding: unicode
  database: desk_development
  pool: 5
  username: desk
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: desk_test
  pool: 5
  username: desk
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: desk_production
  pool: 5
  username: desk
  password: